name: mapmoa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  permission_handler: ^12.0.0+1
  geolocator: ^9.0.2
  flutter:
    sdk: flutter

  #FCM 관련 패키지 추가
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  flutter_local_notifications: ^16.3.1+1

  # 웹소켓 관련 패키지
  stomp_dart_client: ^2.0.0  # 최신 버전 확인 필요

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7         # ✅ 이미지 선택용
  dio: ^5.4.0                  # ✅ HTTP 통신용
  http_parser: ^4.0.2          # ✅ MIME 설정용
  fluttertoast: ^8.2.4         # ✅ 토스트 메시지
  flutter_naver_map: ^1.3.1   # ✅ 네이버 지도 플러그인
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_native_splash: ^2.3.5

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/map.png
    - assets/logoo.png
    - assets/location.png
    - assets/markers/blue.png
    - assets/markers/green.png
    - assets/markers/orange.png
    - assets/markers/purple.png
    - assets/markers/red.png
    - assets/markers/yellow.png
    - assets/markers/event.png